version: '3'
services:
  mintr:
    image: mrcide/mintr:${API_BRANCH}
    restart: unless-stopped
  mint:
    depends_on:
    - mintr
    image: mrcide/mint:${APP_BRANCH}
    restart: unless-stopped
    volumes:
    - ./mint/src/app/static/scripts/test.properties:/etc/mint/config.properties:ro
  proxy:
    command: app:8080 ${SERVER}.dide.ic.ac.uk 80 443
    image: reside/proxy-nginx:master
    links:
    - mint:app
    ports:
    - 80:80
    - 443:443
    restart: unless-stopped
    volumes:
    - mint-tls:/run/proxy

volumes:
  mint-tls:
    external: true

